### ISSUE TITLE
【対応中】AB Testin Global Edition が有効でも AB Testing のバナーが表示される

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-admin-banners#11]
![スクリーンショット 2024-12-18 21 16 48](https://github.com/user-attachments/assets/cd0249c2-ebac-49d9-9267-23ee6f3a1ec8)

登録バナーのスラッグに global がない事が原因かと（・ｗ・

↓ 変更方法はここに書いてありますんー。たぶん。
https://github.com/vektor-inc/vk-admin-banners

**Comment by akito-38** [comment]
@kurudrive 
対応して動作確認致しました。
問題無いかと思いますので、クローズいたします。
