### ISSUE TITLE
G3 Pro Unit バナー

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-admin-banners#2]
コンテンツの作成やサイトのカスタマイズをもっと簡単に！
Lightning G3 Pro Unit

https://lightning.vektor-inc.co.jp/lightning-g3-pro-unit

**Comment by goutetsuguma** [comment]
ひとまずこちらにデータ作成しました（わかりずらい場所に作ってしまったので、あとで移動するかもです）
他のAdminバナーとの統一感をだしたいとは思うのですが、、、
・下に帯があるバナーは、過去のadminバナーでよく見かけました
・右にVKマークがあるバナーは、拡張デザインキットの　VekanとEvergreenのバナーに入っています。
https://www.figma.com/file/gOC256CjytFofrUj5Po5zU/banner?node-id=3%3A88
いろいろご意見いただけますとうれしいですmm

追記
わ！Figmaファイルの修正ありがとうございます！
テキストの量がおおくてなんか収まり悪かったのですが、これなら収まり良くていいですね！


![ad_banner-g3-unit-02](https://user-images.githubusercontent.com/5525368/135819973-c473a27d-c438-4711-b115-5d3b8025fd2d.jpeg)
![ad_banner-g3-unit](https://user-images.githubusercontent.com/5525368/135819982-0253e093-1b46-4f11-aa82-e76340cdce0b.jpeg)

**Comment by kurudrive** [comment]
@goutetsuguma 

ありがとうございます！
右下のVKロゴや下の青帯は整合性でなるほどと思いました！

掲載至急と考えたので一旦暫定で掲載しました。

けれども、

* 実際の表示サイズが 180 * 150 なので文字をもっと大きくしないと潰れてしまう。
* そもそも「Lightning G3 Pro Unit」が正式名称なので、Lightning Pro Unit の表記だとやはり違和感がある。

という大きな難題があり、僕がちょちょいと調整するレベルでは無理でした...。

やっぱり G3 ロゴ を作らないといろいろ厳しいかもしれない...（＝ｗ＝；

Cc: @miminari @ChiakiKouno @kaorock72

**Comment by goutetsuguma** [comment]
そうですね、、ぱっとみた時に「Lightning Pro Unit 」なので、どこかに正式名称がないといけないなと思って、下に「機能拡張プラグインLightning G3 Pro Unit」の文字をおいたのですが、ここは長すぎてバランスが悪く、、汗
G3 ロゴがあるとこの問題も解決するのでいいなと思いました！

**Comment by goutetsuguma** [comment]
![ad_banner-g3-unit](https://user-images.githubusercontent.com/5525368/156122604-99f44741-0e50-47d0-a6b7-8b3b402d0cca.jpg)
![ad_banner-g3-unit-03](https://user-images.githubusercontent.com/5525368/156313561-2b1d9b29-156f-4e17-b652-1953b3f4ba4f.jpg)
▼実際の表示サイズ(180×150)
![ad_banner-g3-unit-03-180](https://user-images.githubusercontent.com/5525368/157199906-a96dcef1-8f67-43d1-9373-2939c334ca99.jpg)

@kurudrive 
バナーこちらに貼り付けたんでした。。。

今実際の表示サイズ見たら、一番下の文字が長くて微妙ですね。。。文言変えようかな。。。なにがいいかな。。。
一番

**Comment by goutetsuguma** [comment]
![ad_banner-g3-unit-03](https://user-images.githubusercontent.com/5525368/158754297-21bc538d-dd6f-4ac3-972f-a9084979a41a.png)

#### 実際の表示サイズ
![ad_banner-g3-unit-03-180](https://user-images.githubusercontent.com/5525368/158754311-d4d6c4ac-6957-4bc3-acd4-d9a7d50146d3.png)

@kurudrive 
みにくかった下の文字の文言を調整してみました。
お手隙の時でいいのでご確認お願いします🙇‍♂️

**Comment by kurudrive** [comment]
@goutetsuguma 一番上と下の文字ちょっと小さくない？
上の文言とか文字数減らしてもう少し文字大きくしたほうが良いかと。

**Comment by goutetsuguma** [comment]
![ad_banner-g3-unit-03](https://user-images.githubusercontent.com/5525368/158771026-3e67677f-e02a-403b-8a80-a5d7cd54d33b.png)
### 実際のサイズ
![ad_banner-g3-unit-03-180](https://user-images.githubusercontent.com/5525368/158771053-961dde62-cd22-4003-b241-728aff478679.png)

@kurudrive 
文字数減らして大きくしてみました！
お手隙の際にご確認お願いしますmm

**Comment by kurudrive** [comment]
@goutetsuguma ありがとうございます。これでいきましょう！
