### ISSUE TITLE
【確認待ち】VK Filter Search のバナー追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-admin-banners#3]
https://www.vektor-inc.co.jp/service/wordpress-plugins/vk-filter-search/?rel=vkadmin

- [x] 日本語版
- [x] 英語版

絞り込み検索が簡単に設置できる
VK Filter Search

**Comment by kurudrive** [comment]
@goutetsuguma こちらG3ロゴの後でよろしくお願いいたします。

■ 日本語無料版のバナー

- [x] ロゴ下の文言を「無料で使える絞り込み検索ブロック」に変更
- [x] ロゴ下の文言をもう少しだけ大きくして太くする（ダッシュボード上だとかすれる）
- [x] 無料 が目立つようにマークなどつける

■ 日本語 Pro バナー
- [x] ロゴ下の文言を「高度な絞り込み検索が簡単に設置可能」に変更
- [x] ロゴ下の文言をもう少しだけ大きくして太くする（ダッシュボード上だとかすれる）

特に気になる点がなければそのまま配信でOK

**Comment by goutetsuguma** [comment]
@kurudrive そのままmainへプッシュ済みです。ご確認お願いいたします
![14570721-116e54a8da156909269026c8845c9b39](https://user-images.githubusercontent.com/5525368/136150158-36a15eb4-49d1-437a-89e0-24a58b3b7a45.png)

**Comment by kurudrive** [comment]
@goutetsuguma ありがとうございましたー！
