### ISSUE TITLE
Filter Search の 無料版とPro版の出し分け処理が必要

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-admin-banners#4]
Pro版がインストールされてたら無料版はインストールされてなくても無料版のバナーを表示しないようにしたい。

なので、特定のプラグイン・テーマがインストールされてたら表示しない ための除外用パラメーターがあった方が良いかも。
そのパラメーターに配列で除外要件を格納し、マッチした場合はバナーを表示しないみたいな。

あーこれ、vk-admin 側で実装だったかも。

**Comment by drill-lancer** [comment]
@kurudrive 
そのとおり VK Admin 側で実装しました。
https://github.com/vektor-inc/vektor-wp-libraries/pull/80
