### ISSUE TITLE
G3 Pro Unit や VEKUAN など、Lightning G3 のプラグインはテーマが Lightning の時のみ表示にしたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-admin-banners#5]
* X-T9 の時に表示されてもしょうがないため
* バナーが増えてきてバナーだらけになるため

**Comment by drill-lancer** [comment]
@kurudrive 
すでに対応した覚えがあるのですが・・・

**Comment by kurudrive** [comment]
@drill-lancer 
|・）つ「 https://demo.dev3.biz/x-t9/ 」

**Comment by drill-lancer** [comment]
@kurudrive 
VK Admin がふるいだけかと・・・

**Comment by kurudrive** [comment]
@drill-lancer 確認しました。
現状リリース済みのプラグインとしては最新版では出るものの、
今回の Composer版 では解消されました。

この件は最近バナー関連のプルリクは記憶になかったので
そもそも未対応なのか？
マージ済みなのにリリースしていないだけなのか？
まだ未マージの状態なのか？
が不明なので issue 立てました。

「対応した覚えがある」とか「VK Adminがふるいだけ」ではなく、
これは今回の Composer 版から反映されたのですか？
それとも vektor-wp-lib で修正されてたいけど各プラグインに展開されてない状態だった感じ？
vk-admin-banner 側ではそれらしいプルリクがなかったので...。

**Comment by drill-lancer** [comment]
@kurudrive 
ライブラリ側でプルリク出してマージされた
⇒ Composer で管理したい by @kurudrive https://github.com/vektor-inc/vektor-wp-libraries/issues/112
⇒ 現状 Composer 版のみ反映されている状態

ですね。

**Comment by kurudrive** [comment]
@drill-lancer 了解です。ありがとうございます！
